import ts from 'typescript';
import { literalNode } from './literal-node';
import { serialize } from './serialize';

/*
const __RΦ = {
    m: (k, v) => (t, ...a) => t && Reflect.metadata ? Reflect.metadata(k, v)(t, ...a) : void 0,
    f: (f, d, n) => (d.forEach(d => d(f)), Object.defineProperty(f, "name", { value: n, writable: false }), f),
    c: (c, d, dp, dsp, n) => (
        d.forEach(d => d(c)),
        dp.forEach(([p, d]) => d(c.prototype, p)),
        dsp.forEach(([p, d]) => d(c, p)),
        n ? Object.defineProperty(c, "name", { value: n, writable: false }) : undefined,
        c
    ),
    a: id => {
        __RΦ.tr = __RΦ.tr ?? {};
        if (__RΦ.tr[id])
            return __RΦ.tr[id];

        __RΦ.tr[id] = {};
        return Object.assign(__RΦ.tr[id], __RΦ.t[id]());
    }
    t: { [79]: { RΦ: t => ({ TΦ: "F", r: __RΦ.a(81), p: [], f: "" }) }, [81]: { TΦ: "5", name: "A" } }
};


 */

export function rtStore(typeMap: Map<number, ts.Expression>) {
    const factory = ts.factory;

    let typeEntries = Array.from(typeMap.entries()).map(([i, t]) => factory.createPropertyAssignment(
        factory.createComputedPropertyName(ts.factory.createNumericLiteral(i)),
        t
    ));
    let typeStore = factory.createObjectLiteralExpression(typeEntries);

    // -----------------------

    return serialize({
        m: literalNode(factory.createArrowFunction(
            undefined,
            undefined,
            [
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier("k"),
                    undefined,
                    undefined,
                    undefined
                ),
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier("v"),
                    undefined,
                    undefined,
                    undefined
                )
            ],
            undefined,
            factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
            factory.createArrowFunction(
                undefined,
                undefined,
                [
                    factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        factory.createIdentifier("t"),
                        undefined,
                        undefined,
                        undefined
                    ),
                    factory.createParameterDeclaration(
                        undefined,
                        factory.createToken(ts.SyntaxKind.DotDotDotToken),
                        factory.createIdentifier("a"),
                        undefined,
                        undefined,
                        undefined
                    )
                ],
                undefined,
                factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                factory.createConditionalExpression(
                    factory.createBinaryExpression(
                        factory.createIdentifier("t"),
                        factory.createToken(ts.SyntaxKind.AmpersandAmpersandToken),
                        factory.createPropertyAccessExpression(
                            factory.createIdentifier("Reflect"),
                            factory.createIdentifier("metadata")
                        )
                    ),
                    factory.createToken(ts.SyntaxKind.QuestionToken),
                    factory.createCallExpression(
                        factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                                factory.createIdentifier("Reflect"),
                                factory.createIdentifier("metadata")
                            ),
                            undefined,
                            [
                                factory.createIdentifier("k"),
                                factory.createIdentifier("v")
                            ]
                        ),
                        undefined,
                        [
                            factory.createIdentifier("t"),
                            factory.createSpreadElement(factory.createIdentifier("a"))
                        ]
                    ),
                    factory.createToken(ts.SyntaxKind.ColonToken),
                    factory.createVoidExpression(factory.createNumericLiteral("0"))
                )
            )
        )),
        f: literalNode(factory.createArrowFunction(
            undefined,
            undefined,
            [
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier("f"),
                    undefined,
                    undefined,
                    undefined
                ),
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier("d"),
                    undefined,
                    undefined,
                    undefined
                ),
                factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier("n"),
                    undefined,
                    undefined,
                    undefined
                )
            ],
            undefined,
            factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
            factory.createParenthesizedExpression(factory.createBinaryExpression(
                factory.createBinaryExpression(
                    factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                            factory.createIdentifier("d"),
                            factory.createIdentifier("forEach")
                        ),
                        undefined,
                        [factory.createArrowFunction(
                            undefined,
                            undefined,
                            [factory.createParameterDeclaration(
                                undefined,
                                undefined,
                                factory.createIdentifier("d"),
                                undefined,
                                undefined,
                                undefined
                            )],
                            undefined,
                            factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                            factory.createCallExpression(
                                factory.createIdentifier("d"),
                                undefined,
                                [factory.createIdentifier("f")]
                            )
                        )]
                    ),
                    factory.createToken(ts.SyntaxKind.CommaToken),
                    factory.createCallExpression(
                        factory.createPropertyAccessExpression(
                            factory.createIdentifier("Object"),
                            factory.createIdentifier("defineProperty")
                        ),
                        undefined,
                        [
                            factory.createIdentifier("f"),
                            factory.createStringLiteral("name"),
                            factory.createObjectLiteralExpression(
                                [
                                    factory.createPropertyAssignment(
                                        factory.createIdentifier("value"),
                                        factory.createIdentifier("n")
                                    ),
                                    factory.createPropertyAssignment(
                                        factory.createIdentifier("writable"),
                                        factory.createFalse()
                                    )
                                ],
                                false
                            )
                        ]
                    )
                ),
                factory.createToken(ts.SyntaxKind.CommaToken),
                factory.createIdentifier("f")
            ))
        )),
        c: literalNode(
            factory.createArrowFunction(
                undefined,
                undefined,
                [
                    factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        factory.createIdentifier("c"),
                        undefined,
                        undefined,
                        undefined
                    ),
                    factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        factory.createIdentifier("d"),
                        undefined,
                        undefined,
                        undefined
                    ),
                    factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        factory.createIdentifier("dp"),
                        undefined,
                        undefined,
                        undefined
                    ),
                    factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        factory.createIdentifier("dsp"),
                        undefined,
                        undefined,
                        undefined
                    ),
                    factory.createParameterDeclaration(
                        undefined,
                        undefined,
                        factory.createIdentifier("n"),
                        undefined,
                        undefined,
                        undefined
                    )
                ],
                undefined,
                factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                factory.createParenthesizedExpression(factory.createBinaryExpression(
                    factory.createBinaryExpression(
                        factory.createBinaryExpression(
                            factory.createBinaryExpression(
                                factory.createCallExpression(
                                    factory.createPropertyAccessExpression(
                                        factory.createIdentifier("d"),
                                        factory.createIdentifier("forEach")
                                    ),
                                    undefined,
                                    [factory.createArrowFunction(
                                        undefined,
                                        undefined,
                                        [factory.createParameterDeclaration(
                                            undefined,
                                            undefined,
                                            factory.createIdentifier("d"),
                                            undefined,
                                            undefined,
                                            undefined
                                        )],
                                        undefined,
                                        factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                        factory.createCallExpression(
                                            factory.createIdentifier("d"),
                                            undefined,
                                            [factory.createIdentifier("c")]
                                        )
                                    )]
                                ),
                                factory.createToken(ts.SyntaxKind.CommaToken),
                                factory.createCallExpression(
                                    factory.createPropertyAccessExpression(
                                        factory.createIdentifier("dp"),
                                        factory.createIdentifier("forEach")
                                    ),
                                    undefined,
                                    [factory.createArrowFunction(
                                        undefined,
                                        undefined,
                                        [factory.createParameterDeclaration(
                                            undefined,
                                            undefined,
                                            factory.createArrayBindingPattern([
                                                factory.createBindingElement(
                                                    undefined,
                                                    undefined,
                                                    factory.createIdentifier("p"),
                                                    undefined
                                                ),
                                                factory.createBindingElement(
                                                    undefined,
                                                    undefined,
                                                    factory.createIdentifier("d"),
                                                    undefined
                                                )
                                            ]),
                                            undefined,
                                            undefined,
                                            undefined
                                        )],
                                        undefined,
                                        factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                        factory.createCallExpression(
                                            factory.createIdentifier("d"),
                                            undefined,
                                            [
                                                factory.createPropertyAccessExpression(
                                                    factory.createIdentifier("c"),
                                                    factory.createIdentifier("prototype")
                                                ),
                                                factory.createIdentifier("p")
                                            ]
                                        )
                                    )]
                                )
                            ),
                            factory.createToken(ts.SyntaxKind.CommaToken),
                            factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createIdentifier("dsp"),
                                    factory.createIdentifier("forEach")
                                ),
                                undefined,
                                [factory.createArrowFunction(
                                    undefined,
                                    undefined,
                                    [factory.createParameterDeclaration(
                                        undefined,
                                        undefined,
                                        factory.createArrayBindingPattern([
                                            factory.createBindingElement(
                                                undefined,
                                                undefined,
                                                factory.createIdentifier("p"),
                                                undefined
                                            ),
                                            factory.createBindingElement(
                                                undefined,
                                                undefined,
                                                factory.createIdentifier("d"),
                                                undefined
                                            )
                                        ]),
                                        undefined,
                                        undefined,
                                        undefined
                                    )],
                                    undefined,
                                    factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                                    factory.createCallExpression(
                                        factory.createIdentifier("d"),
                                        undefined,
                                        [
                                            factory.createIdentifier("c"),
                                            factory.createIdentifier("p")
                                        ]
                                    )
                                )]
                            )
                        ),
                        factory.createToken(ts.SyntaxKind.CommaToken),
                        factory.createConditionalExpression(
                            factory.createIdentifier("n"),
                            factory.createToken(ts.SyntaxKind.QuestionToken),
                            factory.createCallExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createIdentifier("Object"),
                                    factory.createIdentifier("defineProperty")
                                ),
                                undefined,
                                [
                                    factory.createIdentifier("c"),
                                    factory.createStringLiteral("name"),
                                    factory.createObjectLiteralExpression(
                                        [
                                            factory.createPropertyAssignment(
                                                factory.createIdentifier("value"),
                                                factory.createIdentifier("n")
                                            ),
                                            factory.createPropertyAssignment(
                                                factory.createIdentifier("writable"),
                                                factory.createFalse()
                                            )
                                        ],
                                        false
                                    )
                                ]
                            ),
                            factory.createToken(ts.SyntaxKind.ColonToken),
                            factory.createIdentifier("undefined")
                        )
                    ),
                    factory.createToken(ts.SyntaxKind.CommaToken),
                    factory.createIdentifier("c")
                ))
            )
        ),
        a: literalNode(
            factory.createArrowFunction(
                undefined,
                undefined,
                [factory.createParameterDeclaration(
                    undefined,
                    undefined,
                    factory.createIdentifier("id"),
                    undefined,
                    undefined,
                    undefined
                )],
                undefined,
                factory.createToken(ts.SyntaxKind.EqualsGreaterThanToken),
                factory.createBlock(
                    [
                        factory.createExpressionStatement(factory.createBinaryExpression(
                            factory.createPropertyAccessExpression(
                                factory.createIdentifier("__RΦ"),
                                factory.createIdentifier("tr")
                            ),
                            factory.createToken(ts.SyntaxKind.EqualsToken),
                            factory.createBinaryExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createIdentifier("__RΦ"),
                                    factory.createIdentifier("tr")
                                ),
                                factory.createToken(ts.SyntaxKind.QuestionQuestionToken),
                                factory.createObjectLiteralExpression(
                                    [],
                                    false
                                )
                            )
                        )),
                        factory.createIfStatement(
                            factory.createElementAccessExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createIdentifier("__RΦ"),
                                    factory.createIdentifier("tr")
                                ),
                                factory.createIdentifier("id")
                            ),
                            factory.createReturnStatement(factory.createElementAccessExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createIdentifier("__RΦ"),
                                    factory.createIdentifier("tr")
                                ),
                                factory.createIdentifier("id")
                            )),
                            undefined
                        ),
                        factory.createExpressionStatement(factory.createBinaryExpression(
                            factory.createElementAccessExpression(
                                factory.createPropertyAccessExpression(
                                    factory.createIdentifier("__RΦ"),
                                    factory.createIdentifier("tr")
                                ),
                                factory.createIdentifier("id")
                            ),
                            factory.createToken(ts.SyntaxKind.EqualsToken),
                            factory.createObjectLiteralExpression(
                                [],
                                false
                            )
                        )),
                        factory.createReturnStatement(factory.createCallExpression(
                            factory.createPropertyAccessExpression(
                                factory.createIdentifier("Object"),
                                factory.createIdentifier("assign")
                            ),
                            undefined,
                            [
                                factory.createElementAccessExpression(
                                    factory.createPropertyAccessExpression(
                                        factory.createIdentifier("__RΦ"),
                                        factory.createIdentifier("tr")
                                    ),
                                    factory.createIdentifier("id")
                                ),
                                factory.createCallExpression(
                                    factory.createElementAccessExpression(
                                        factory.createPropertyAccessExpression(
                                            factory.createIdentifier("__RΦ"),
                                            factory.createIdentifier("t")
                                        ),
                                        factory.createIdentifier("id")
                                    ),
                                    undefined,
                                    []
                                )
                            ]
                        ))
                    ],
                    true
                )
            )
        ),
        t: literalNode(typeStore)
    });
}